# Generated by Django 3.1.7 on 2021-05-12 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
